import { shortDate } from "./dates.ts";
import { codeSpan, markdownText } from "./markdown.ts";
import { isOpen, type RepoGlossary, type RepoTerm, type RowStatus } from "./repoGlossary.ts";

const TODO_RULE =
  "Don't name code, columns or statuses after either reading. Leave a `TODO(glossary): <term>` at that one point, keep building everything else, and say what you left open.";

const NOTHING_UNSETTLED =
  "- **Unsettled:** nothing in this export. If the task needs a meaning that isn't here, leave a `TODO(glossary): <term>` at that one point and ask.";

const EXACT_TERMS =
  "- Use these exact terms in specs, tickets, code names, filenames and the API surface. Never abbreviate or rename them; if something has no name, ask instead of coining one.";

const BY_CONTEXT = "- A term's meaning depends on its context; never merge meanings across contexts.";

export function claudeSection(glossary: RepoGlossary, asOf: Date): string {
  return [
    "## Domain language (from GLOSSARY.md)",
    "",
    `Generated by DDD Coach, ${shortDate(asOf)}, ${glossary.origin}. Regenerate rather than hand-edit.`,
    "",
    ...settledList(glossary.terms.flatMap(settledLine)),
    "",
    EXACT_TERMS,
    BY_CONTEXT,
    unsettledBullet(glossary.terms.flatMap(unsettledPoint)),
    ...avoidBullet(glossary.terms.flatMap(avoidPoints)),
    "",
  ].join("\n");
}

const settledList = (lines: string[]): string[] =>
  lines.length === 0
    ? ["Settled terms: none yet; see the open questions in `GLOSSARY.md`."]
    : ["Settled terms. Build on these, each in the context named (meanings in `GLOSSARY.md`):", ...lines];

function settledLine({ word, identifiers, rows }: RepoTerm): string[] {
  const settled = rows.filter((row) => !isOpen(row));
  if (settled.length === 0) return [];
  const inCode = identifiers.length === 0 ? "" : `; in code ${identifiers.map(codeSpan).join(", ")}`;
  return [`- ${codeSpan(word)} for ${settled.map(({ context }) => markdownText(context)).join(", ")}${inCode}`];
}

const unsettledBullet = (points: string[]): string =>
  points.length === 0 ? NOTHING_UNSETTLED : `- **Unsettled, don't pick a side:** ${points.join("; ")}. ${TODO_RULE}`;

function unsettledPoint({ word, rows }: RepoTerm): string[] {
  const open = rows.filter(isOpen);
  if (open.length === 0) return [];
  const reasons = new Set(open.map(({ status }) => openReason(status)));
  if (open.length === rows.length && reasons.size === 1) return [`${codeSpan(word)} (${[...reasons][0]})`];
  return [`${codeSpan(word)} for ${open.map(({ context, status }) => `${markdownText(context)} (${openReason(status)})`).join(", ")}`];
}

const openReason = (status: RowStatus): string => (status.kind === "unsettled" ? `Q${status.question}` : "a guess");

const avoidPoints = ({ word, avoid }: RepoTerm): string[] => avoid.map((other) => `${codeSpan(other)} (write ${codeSpan(word)})`);

const avoidBullet = (points: string[]): string[] =>
  points.length === 0 ? [] : [`- **Don't use:** ${points.join(", ")}. The thread uses these for the same meaning as a term in \`GLOSSARY.md\`.`];
