// @vitest-environment node
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { parseReply } from "./replyBlocks.ts";
import { claudeSection } from "./claudeSection.ts";
import { glossaryMarkdown, repoCopiedMessage, repoMarkdown } from "./repoExport.ts";
import { replyGlossary } from "./repoGlossary.ts";
import { rfcDocument } from "./rfcExport.ts";

const AS_OF = new Date(2026, 8, 25, 14, 30);

const glossaryOf = (reply: string) => replyGlossary(rfcDocument(parseReply(reply)));

const WORDS = [
  "Words that don't match",
  '"rebook"',
  "- From thread: Ops (day desk) means a date change with the same carrier is AMENDED.",
  "- Guess: Code counts both rows of a rebook.",
].join("\n");

const LATE = [
  "Words that don't match",
  '"late"',
  "- From thread: Account team means missing the delivery appointment the customer booked.",
  "- From thread: Ops (day desk) means a truck not at pickup by the end of the pickup window.",
  "- From thread: Billing means a load included on the weekly late report.",
  '"on time"',
  "- From thread: Account team means meeting the customer's booked delivery appointment.",
  "",
  "Question for the account team lead and the billing lead, at Friday's service review: For load 7731, which count includes it: the service-credit count or the weekly late report?",
  'From thread: "issued Customer D a service credit for 7731, it\'s on this week\'s late report"',
].join("\n");

describe("claudeSection", () => {
  it("opens with its stamp and the settled terms, then the rules, then what's unsettled", () => {
    const withGuess = LATE.replace('"on time"\n', '"on time"\n- Guess: Code means delivered_at is before the appointment.\n');

    expect(claudeSection(glossaryOf(withGuess), AS_OF)).toBe(
      [
        "## Domain language (from GLOSSARY.md)",
        "",
        "Generated by DDD Coach, 25 Sep 2026, from one coach reply to a pasted thread. Regenerate rather than hand-edit.",
        "",
        "Settled terms. Build on these, each in the context named (meanings in `GLOSSARY.md`):",
        "- `on time` for Account team",
        "",
        "- Use these exact terms in specs, tickets, code names, filenames and the API surface. Never abbreviate or rename them; if something has no name, ask instead of coining one.",
        "- A term's meaning depends on its context; never merge meanings across contexts.",
        "- **Unsettled, don't pick a side:** `late` (Q1); `on time` for Code (a guess). Don't name code, columns or statuses after either reading. Leave a `TODO(glossary): <term>` at that one point, keep building everything else, and say what you left open.",
        "",
      ].join("\n"),
    );
  });

  it("gives a settled term the real identifiers its Code row names from the thread, never a guessed one", () => {
    const report = [
      "Words that don't match",
      '"weekly late report"',
      "- From thread: Billing means the basis for service credits.",
      "- From thread: Code means the late_loads query, where actual_pickup_at is after pickup_window_end.",
      '"on time"',
      "- From thread: Account team means meeting the booked appointment.",
      "- Guess: Code means delivered_at is before delivery_appointment.",
    ].join("\n");
    const section = claudeSection(glossaryOf(report), AS_OF);

    expect(section).toContain("- `weekly late report` for Billing, Code; in code `late_loads`, `actual_pickup_at`, `pickup_window_end`\n");
    expect(section).toContain("- `on time` for Account team\n");
  });

  it("stays within 15 lines for any reply the coach may send, up to its 4 words", () => {
    const meaning = fc.record({
      source: fc.constantFrom("From thread", "Guess"),
      holder: fc.constantFrom("Ops (day desk)", "Ops (night desk)", "Billing", "Account team", "Carrier desk", "Code"),
      identifier: fc.constantFrom("", " via late_loads", " on rebookedFromId"),
    });
    const term = fc.record({ word: fc.constantFrom("late", "on time", "rebook", "booking", "tender"), pair: fc.boolean(), meanings: fc.array(meaning, { minLength: 1, maxLength: 6 }) });
    const reply = fc.record({ terms: fc.array(term, { minLength: 1, maxLength: 4 }), asks: fc.constantFrom("", "late", "rebook") });

    fc.assert(
      fc.property(reply, ({ terms, asks }) => {
        const words = terms.flatMap(({ word, pair, meanings }) => [
          `"${word}"`,
          ...meanings.map(({ source, holder, identifier }) => `- ${source}: ${holder} means a load${identifier}${pair ? `, whether they say "${word}" or "${word}x"` : ""}.`),
        ]);
        const question = asks === "" ? [] : ["", `Question for the ops lead: For load 7731, which ${asks} count is it?`];
        const section = claudeSection(glossaryOf(["Words that don't match", ...words, ...question].join("\n")), AS_OF);

        expect(section.trimEnd().split("\n").length).toBeLessThanOrEqual(15);
      }),
    );
  });

  it("says no term is settled yet when every row is open", () => {
    const allOpen = ["Words that don't match", '"late"', "- From thread: Billing means on the weekly report.", "", "Question for the billing lead: For load 7731, which late count is it?"].join("\n");

    expect(claudeSection(glossaryOf(allOpen), AS_OF)).toContain(
      "Regenerate rather than hand-edit.\n\nSettled terms: none yet; see the open questions in `GLOSSARY.md`.\n\n- Use these exact terms",
    );
  });

  it("names the words not to use last, each with the term to write instead, only when the thread gives any", () => {
    const pending = ["Words that don't match", '"pending"', '- From thread: Front desk means a request nobody has confirmed yet, whether they say "pending" or "unconfirmed".'].join("\n");

    expect(claudeSection(glossaryOf(pending), AS_OF).endsWith(
      "- **Don't use:** `unconfirmed` (write `pending`). The thread uses these for the same meaning as a term in `GLOSSARY.md`.\n",
    )).toBe(true);
    expect(claudeSection(glossaryOf(LATE), AS_OF)).not.toContain("Don't use");
  });

  it("says nothing is unsettled when every row is settled, so the whole task is buildable", () => {
    const settled = ["Words that don't match", '"late"', "- From thread: Billing means a load included on the weekly late report."].join("\n");

    expect(claudeSection(glossaryOf(settled), AS_OF)).toContain(
      "- **Unsettled:** nothing in this export. If the task needs a meaning that isn't here, leave a `TODO(glossary): <term>` at that one point and ask.",
    );
  });
});

describe("repoMarkdown", () => {
  it("puts GLOSSARY.md first and the CLAUDE.md section after it, each labelled with where it goes", () => {
    const glossary = glossaryOf(LATE);

    expect(repoMarkdown(glossary, AS_OF)).toBe(
      [
        "<!-- GLOSSARY.md: save this part as GLOSSARY.md at the root of your repo. -->",
        glossaryMarkdown(glossary, AS_OF),
        "<!-- CLAUDE.md or AGENTS.md: paste this section in. It points at GLOSSARY.md, so there is one copy to keep current. -->",
        claudeSection(glossary, AS_OF),
      ].join("\n"),
    );
  });
});

describe("repoCopiedMessage", () => {
  it.each([
    [0, "Copied for your repo: GLOSSARY.md, then a section for CLAUDE.md."],
    [1, "Copied for your repo: GLOSSARY.md, then a section for CLAUDE.md. 1 term is still unsettled."],
    [2, "Copied for your repo: GLOSSARY.md, then a section for CLAUDE.md. 2 terms are still unsettled."],
  ])("counts %i unsettled terms", (unsettled, message) => {
    expect(repoCopiedMessage(unsettled)).toBe(message);
  });
});

describe("glossaryMarkdown escaping", () => {
  const LIVE = "[x](javascript:alert(1)) <img src=x onerror=alert(1)> `run` a\\b";
  const ESCAPED = "\\[x\\](javascript:alert(1)) \\<img src=x onerror=alert(1)\\> \\`run\\` a\\\\b";

  it("escapes link, HTML and code characters in the term, its cells and the question, as #6 does", () => {
    const reply = [
      "Words that don't match",
      `"hold ${LIVE}"`,
      `- From thread: Ops means ${LIVE} | CONFIRMED.`,
      "",
      `Question for the ops lead: For load 48213, which ${LIVE}?`,
    ].join("\n");
    const markdown = glossaryMarkdown(glossaryOf(reply), AS_OF);

    expect(markdown).toContain(`## hold ${ESCAPED}`);
    expect(markdown).toContain(`| Ops | ${ESCAPED} \\| CONFIRMED. | From thread | Settled |`);
    expect(markdown).toContain(`1. Question for the ops lead: For load 48213, which ${ESCAPED}?`);
  });
});

describe("glossaryMarkdown", () => {
  it("opens with the real export date and where the file came from", () => {
    expect(glossaryMarkdown(glossaryOf(WORDS), AS_OF).split("\n").slice(0, 3)).toEqual([
      "# Glossary",
      "",
      "As of 25 Sep 2026. Exported from DDD Coach, from one coach reply to a pasted thread. When a question below is settled, change its rows here, or export again.",
    ]);
  });

  it("tells coding agents to build what's settled and leave a TODO only at the unsettled point", () => {
    expect(glossaryMarkdown(glossaryOf(WORDS), AS_OF).split("\n")[4]).toBe(
      "**For coding agents:** use these words exactly as defined here. A term's meaning depends on the context named in its row; don't merge meanings across contexts. Build what's settled. Rows marked **Unsettled** have no agreed meaning yet: don't pick one, and don't name code, columns or statuses after either reading. Leave a `TODO(glossary): <term>` at that one point and keep building the rest of the task. Don't introduce a domain term that isn't in this file; ask instead.",
    );
  });

  it("writes each term as a context table, settled rows from the thread and a guess marked unsettled", () => {
    expect(glossaryMarkdown(glossaryOf(WORDS), AS_OF)).toContain(
      [
        "## rebook",
        "",
        "2 meanings by context.",
        "",
        "| Context | Meaning | Source | Status |",
        "|---|---|---|---|",
        "| Ops (day desk) | A date change with the same carrier is AMENDED. | From thread | Settled |",
        "| Code | Guess: Counts both rows of a rebook. | Guess | **Unsettled**, a guess |",
      ].join("\n"),
    );
  });

  it("marks every thread row of a term an open question names unsettled, even for a team it doesn't ask", () => {
    expect(glossaryMarkdown(glossaryOf(LATE), AS_OF)).toContain(
      [
        "| Account team | Missing the delivery appointment the customer booked. | From thread | **Unsettled**, see Q1 |",
        "| Ops (day desk) | A truck not at pickup by the end of the pickup window. | From thread | **Unsettled**, see Q1 |",
        "| Billing | A load included on the weekly late report. | From thread | **Unsettled**, see Q1 |",
      ].join("\n"),
    );
  });

  it("marks every thread row of 'on time' unsettled when Q1 asks about the 'on-time %', whichever teams it asks", () => {
    const onTime = [
      "Words that don't match",
      '"on time"',
      "- From thread: Account team means meeting the customer's booked delivery appointment.",
      "- From thread: Ops (day desk) means a load can recover from a late pickup by delivering before the appointment.",
      "",
      "Question for the account team lead and the billing lead, at Friday's service review: For Customer D load 7731, which on-time % goes in the board pack: the delivery-appointment count or the pickup count?",
    ].join("\n");

    expect(glossaryMarkdown(glossaryOf(onTime), AS_OF)).toContain(
      [
        "| Account team | Meeting the customer's booked delivery appointment. | From thread | **Unsettled**, see Q1 |",
        "| Ops (day desk) | A load can recover from a late pickup by delivering before the appointment. | From thread | **Unsettled**, see Q1 |",
      ].join("\n"),
    );
  });

  it("counts a plural in the question as naming the term, but not a longer word that starts with it", () => {
    const booking = ["Words that don't match", '"booking"', "- From thread: Finance means a load it can invoice.", '"book"', "- From thread: Ops means to take a load."].join("\n");
    const markdown = glossaryMarkdown(glossaryOf(`${booking}\n\nQuestion for the finance lead: For load 48213, how many bookings does it count?`), AS_OF);

    expect(markdown).toContain("| Finance | A load it can invoice. | From thread | **Unsettled**, see Q1 |");
    expect(markdown).toContain("| Ops | To take a load. | From thread | Settled |");
  });

  it("never counts a term with no letters or digits as named by a question", () => {
    const symbol = ["Words that don't match", '"%"', "- From thread: Finance means the on-time share."].join("\n");

    expect(glossaryMarkdown(glossaryOf(`${symbol}\n\nQuestion for the finance lead: For load 48213, which count is it?`), AS_OF)).toContain(
      "| Finance | The on-time share. | From thread | Settled |",
    );
  });

  it("labels a row with no named team 'Team unclear'", () => {
    const unnamed = [
      "Words that don't match",
      '"rebook"',
      "- From thread: a rebook keeps the ref.",
      "- From thread: Ops (day desk) means a date change with the same carrier is AMENDED.",
      "",
      "Question for the carrier desk lead, at Friday's review: For load 48213, does a rebook keep the ref?",
    ].join("\n");

    expect(glossaryMarkdown(glossaryOf(unnamed), AS_OF)).toContain(
      [
        "| Team unclear | A rebook keeps the ref. | From thread | **Unsettled**, see Q1 |",
        "| Ops (day desk) | A date change with the same carrier is AMENDED. | From thread | **Unsettled**, see Q1 |",
      ].join("\n"),
    );
  });

  it("lists under a term the other words the thread uses for the same meaning, as the coach names them in one line", () => {
    const pending = [
      "Words that don't match",
      '"pending"',
      '- From thread: Front desk means a request nobody has confirmed yet, whether they say "pending" or "unconfirmed".',
      "- From thread: Billing means a request it can't charge for yet.",
    ].join("\n");

    expect(glossaryMarkdown(glossaryOf(pending), AS_OF)).toContain(
      "## pending\n\n2 meanings by context.\n\nDon't use: `unconfirmed`. The thread uses it for the same meaning; write `pending` instead.\n\n| Context",
    );
  });

  it("says 'them' when the thread uses more than one other word", () => {
    const reply = ["Words that don't match", '"pending"', '- From thread: Front desk means an unconfirmed request, whether they say "pending", "tbc" or "unconfirmed".'].join("\n");

    expect(glossaryMarkdown(glossaryOf(reply), AS_OF)).toContain(
      "Don't use: `tbc`, `unconfirmed`. The thread uses them for the same meaning; write `pending` instead.",
    );
  });

  it.each([
    ["a guess names the pair", '- Guess: Front desk means an unconfirmed request, whether they say "pending" or "unconfirmed".'],
    ["the quoted words don't include the term", '- From thread: Ops means a load marked "REBOOKED" or "AMENDED".'],
  ])("adds no Don't use line when %s, so no other word is ever invented", (_case, line) => {
    const reply = ["Words that don't match", '"pending"', line].join("\n");

    expect(glossaryMarkdown(glossaryOf(reply), AS_OF)).not.toContain("Don't use:");
  });

  it("says a term with one row has one meaning recorded", () => {
    expect(glossaryMarkdown(glossaryOf(LATE), AS_OF)).toContain("## on time\n\nOne meaning recorded.\n");
  });

  it("ends with the open questions, numbered, each with its thread lines", () => {
    expect(glossaryMarkdown(glossaryOf(LATE), AS_OF).endsWith(
      [
        "## Open questions",
        "",
        "1. Question for the account team lead and the billing lead, at Friday's service review: For load 7731, which count includes it: the service-credit count or the weekly late report?",
        "   - From thread: \"issued Customer D a service credit for 7731, it's on this week's late report\"",
        "",
      ].join("\n"),
    )).toBe(true);
  });
});
