import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = new URL("../../work/ddd-reference-2015.txt", import.meta.url);
const MODULE = new URL("./dddReference.ts", import.meta.url);

const text = readFileSync(SOURCE, "utf8");
const header = "// Generated by server/knowledge/build.ts from work/ddd-reference-2015.txt. Don't edit by hand.\n";
writeFileSync(MODULE, `${header}export const DDD_REFERENCE = ${JSON.stringify(text)};\n`);
console.log(`wrote server/knowledge/dddReference.ts (${text.length} chars)`);
