from pathlib import Path
p=Path('outputs/ddd-coach-plan.html')
s=p.read_text()
replacements={
'Confirmed baseline: developers new to DDD, leaving with a first event map.':'Confirmed baseline: developers new to DDD, mapping one business workflow with a key exception and shared vocabulary.',
'Confirmed: developers new to DDD, a first event map, live coaching, basic visuals, text in early slices, then voice by default.':'Confirmed: developers new to DDD; one workflow, a key exception, and shared vocabulary; Eazy Freight as the test domain; text first, then voice; Katacombs sensors after slice 4.',
'Twelve small, testable slices':'Thirteen slices · focus on slice 1',
'Each slice adds one observable behavior.':'Each product slice adds one observable behavior. Slice 5 introduces development sensors in separate, testable steps.',
"scope:'events',example:'',notes:'',slice:0":"scope:'workflow',example:'Eazy Freight: help me map a booking from customer request to customer confirmation, including what happens when a carrier rejects it.',notes:'Open: should the coach discover Eazy Freight through my answers or start with a short source-based briefing?',slice:0",
"beginner:{audience:'beginner',style:'guided',scope:'events'}":"beginner:{audience:'beginner',style:'guided',scope:'workflow'}",
"title:'Show a first event map'":"title:'Recap the workflow and exception'",
'A recap action shows an ordered text event map with unresolved questions; alternative exercises use a matching text summary.':'A recap action shows one ordered business workflow, its key exception, shared vocabulary, and unresolved questions.',
'Compare the event map with the log. Its event order matches the visitor’s account; uncertain ordering and proposed events are labeled.':'For Eazy Freight, recap the booking flow and carrier rejection/resubmission branch. Preserve the visitor’s meaning of request, submission, carrier confirmation, and customer confirmation; mark unknowns.',
'help developers new to DDD leave with a first ordered text event map through guided questions':'help developers new to DDD map one business workflow with a key exception and shared vocabulary through guided questions',
'The beginner audience and first event map are confirmed. Coaching style, providers, hosting, and retention remain provisional; control changes explore alternatives. This brief is a planning artifact, not authorization to implement all twelve slices.':'The beginner audience, workflow outcome, Eazy Freight test domain, and sensor integration after slice 4 are confirmed. Coaching details, providers, hosting, and retention remain provisional. Focus implementation planning on slice 1; this is not authorization to implement the whole roadmap.',
'1. Confirmed: developers new to DDD; a first event map of their product.<br>2. Should the coach lead an exercise or follow an open conversation?':'1. Confirmed: beginners; one workflow, a key exception, and shared vocabulary.<br>2. Should Eazy Freight context be discovered in conversation or supplied as a short briefing?',
'DDD Coach · Draft 01':'DDD Coach · Draft 02',
"state.slice<10?":"state.slice<11?",
"state.slice>=5&&state.slice<10":"state.slice>=6&&state.slice<11",
"Object.assign(state,DEFAULTS,presets[key]);":"Object.assign(state,presets[key],{slice:0});",
"$('copy').onclick=copyBrief;render();":"$('copy').onclick=copyBrief;\nfor(const key of ['audience','style','scope','example','notes'])$(key).value=state[key];\nrender();",
'Proposed test: a visitor brings a real domain problem, makes one modeling decision, and explains why it helps.':'Proposed test: a beginner maps Eazy Freight’s booking workflow, explains the carrier rejection/resubmission branch, and distinguishes carrier confirmation from customer confirmation.'
}
for a,b in replacements.items():
    assert a in s,a
    s=s.replace(a,b)
sensor="""{title:'Bring in Katacombs sensors',phase:'Development',change:'Adopt the source repository’s structural, behavioral, and design feedback loop in the coach app; see steps 5a–5d below.',check:'Seed one temporary fault per tier, observe a finding with useful guidance and trigger evidence, then repair it. Missing tools report unavailable, never a false pass.',exclude:'Development tooling only. No sensors dashboard in the coaching UI; no kata game code or Eazy Freight app integration.'},
"""
s=s.replace("{title:'Hear a reply'",sensor+"{title:'Hear a reply'",1)
section="""<section class="panel"><h2>Slice 1 · ready-to-build boundary</h2><p><strong>One text field → one real AI reply in a log.</strong> A page, a server endpoint, and a provider call. No conversation memory until slice 2.</p><ul><li>Submit by button or Enter. Reject blank input; show the sent message and a pending state.</li><li>Allow one request at a time. On success, append exactly one AI reply.</li><li>On provider failure, show an inline error and Retry for the same message; preserve the message without duplicating it in the log.</li><li>Keep the provider credential on the server. Treat messages and replies as text when rendering.</li><li>Verify success and failure/retry behavior with a controllable provider substitute, then run one real-provider smoke test. Provider, model, and credential setup remain to be chosen.</li></ul><p class="note">The whole-session learning outcome arrives through slices 2–4. Slice 1 proves the real request/reply connection only. Start with one thin provider adapter; generalize it only when the next integration needs it.</p></section>
<section class="panel"><h2>Eazy Freight · one workflow to learn</h2><p><strong>Suggested boundary:</strong> booking request → carrier submission → carrier confirmation → customer confirmation. <strong>Key exception:</strong> carrier rejection → revised submission.</p><p><strong>Words to clarify:</strong> customer, shipper, consignee, carrier, booking request, carrier confirmation, customer confirmation. The coach should ask what these mean to the visitor before treating them as shared language.</p><div class="mock"><span class="eyebrow">First test message</span><p>We’re building Eazy Freight for a freight forwarder. Customers ask us to arrange cargo shipments. We request space from a carrier, record its answer, and tell the customer. Help me understand this workflow.</p></div><details><summary>Facilitator’s source notes</summary><p>The supplied shipment trace describes a larger ocean-export journey. The booking subset is verified against <code>Booking.java</code>: <code>submitTo</code> accepts requested or rejected bookings; <code>recordCarrierRejection</code> records rejection; <code>recordCarrierConfirmation</code> and <code>sendConfirmationToCustomer</code> are separate transitions. These are observations of source, not a runtime validation or a claim about universal freight practice.</p><p>Trace: <a href="file://~/explanations/2026-09-24-explanation-eazy-freight-shipment-trace.html">Eazy Freight shipment trace</a><br>Repository resolved to <code>~/personal/eazy-freight</code>. The requested <code>../eazy-freight</code> is not present relative to this planning folder.</p><p>Source files: <code>src/main/java/com/eazyfreight/booking/domain/Booking.java</code>; <code>docs/eazy-freight-domain-summary-v3.md</code>. Pending interview choice: use these as evaluator context, or provide a small briefing to the coach. No repository ingestion or indexing in slice 1.</p></details></section>
<section class="panel"><h2>Slice 5 · sensors before speech</h2><p>Source: <code>~/personal/katacombs-kata-ts</code>. Preserve its <strong>detect → coach → trigger</strong> behavior, including the evidence that a sensor actually ran.</p><details open><summary>5a · Make the integration easy</summary><p>Inventory the source install recipe and dependencies; map source/test paths and runtime hooks to the coach app. If the app needs structural preparation, make that a separate behavior-preserving refactor commit. Adapt project-specific sensor paths and rules without importing kata features. Keep existing app checks green.</p></details><details><summary>5b · Wire cheap feedback</summary><p>Bring over formatting, coached ESLint rules, duplication, secret scanning, and their required guides/report helpers. Wire the supported edit hook. Introduce a temporary structural violation and confirm both the message and hook liveness; fix it and confirm the finding clears. Use synthetic fixtures for scanner checks.</p></details><details><summary>5c · Wire behavior feedback</summary><p>Adapt typechecking, tests, and changed-source mutation testing to the end-of-turn trigger. Verify a broken request/retry behavior fails and a deliberately weak assertion leaves a detectable survivor. Record scope and unavailable states so a skipped or stale run cannot look like a pass.</p></details><details><summary>5d · Close the feedback loop</summary><p>Add the gated design review, recorded findings, docs check at the completion/commit boundary, and sensors doctor. Prove registrations resolve and hooks actually fire in this environment. Keep an explicit check command as a diagnostic path; do not claim automatic integration from configuration files alone.</p></details><p class="muted">Source references: README.md, SENSORS.md, context/sensor-triggers.md, package.json, .codex/hooks.json, .husky/pre-commit, and scripts/sensors-doctor.mjs. Follow INSTALL.md during implementation. Sensor integration is planned here; nothing has been installed into either source repository.</p></section>
"""
s=s.replace('<section class="panel"><h2>Coaching contract</h2>',section+'<section class="panel"><h2>Coaching contract</h2>',1)
s=s.replace("if(state.slice>0)parts.push", "parts.push('Use ~/personal/eazy-freight and ~/explanations/2026-09-24-explanation-eazy-freight-shipment-trace.html as the local domain references. Place Katacombs sensor integration at slice 5, after the workflow recap and before speech: prepare paths in a separate refactor commit if needed, then integrate structural, behavioral, and gated design feedback with coaching messages and verified triggers. Source: ~/personal/katacombs-kata-ts.');\n if(state.slice>0)parts.push",1)
p.write_text(s)
